[default]
extend-ignore-identifiers-re = ["[rR]atatui"]
extend-ignore-re = ["\\(L\\)ine", "\\(E\\)nvironment"]

[default.extend-words]
"Sur" = "Sur"
"inh" = "inh" # abbr for inherited
"PARM" = "PARM"
"ommand" = "ommand" # (C)ommand

[files]
extend-exclude = [
    "include",
    "crates/perfetto-trace-proto/perfetto"
]
